# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Unit Tests (nightly)

on:
  schedule:
    # 10 am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  workflow_dispatch: {}

jobs:
  run-unittests-python:
    name: Unit Tests Python
    uses: ./.github/workflows/unittests_python.yml
    with:
      trigger-sha: ${{ github.sha }}
